library my_prj.globals;

final resources= [
'ARTICLES',
'MUSIC',
'VIDEOS',
'BOOKS'
];
final collections = [
  'ANXIETY',
  'DEPRESSION',
  'LONELINESS',
  'ABUSE',
  'ADDICTION',
  'SELF-HARM',
  'RELATIONSHIPS'
];
final collectionfaq = [
  'ANXIETY',
  'What is anxiety?',
  'ANXIETY',
  'What are panic attacks?',
  'ANXIETY',
  'What’s the difference between anxiety and being stressed?',
  'ANXIETY',
  'Who can I talk to about my anxiety?',
  'ANXIETY',
  'How common is anxiety?',
  'DEPRESSION',
  'What is depression?',
  'DEPRESSION',
  'Is depression curable?',
  'DEPRESSION',
  'What causes depression?',
  'DEPRESSION',
  'Does depression go away on its own?',
  'DEPRESSION',
  'Who can I talk to about my depression?',
  'LONELINESS',
  'What is loneliness?',
  'LONELINESS',
  'Im feeling lonely.',
  'LONELINESS',
  'Why am I having suicidal thoughts?',
  'LONELINESS',
  'Where can I find people like me?',
  'LONELINESS',
  'Nobody Likes Me',
  'ABUSE',
  'What is gaslighting?',
  'ABUSE',
  'My family members are abusive',
  'ABUSE',
  'What is trauma?',
  'ADDICTION',
  'What is addiction?',
  'ADDICTION',
  'How can I stop drinking?',
  'ADDICTION',
  'I feel out of control',
  'SELF-HARM',
  'How do I stop harming myself?',
  'SELF-HARM',
  'How can I tell someone I’m harming myself?',
  'SELF-HARM',
  'Am I harming myself? Types of self-harm',
  'RELATIONSHIPS',
  'How can connecting with others help my mental health?'
  
  
];
final faqs = [
  'What is anxiety?',
  'What are panic attacks?',
  'What’s the difference between anxiety and being stressed?',
  'Who can I talk to about my anxiety?',
  'How common is anxiety?',
  'What is depression?',
  'Is depression curable?',
  'What causes depression?',
  'Does depression go away on its own?',
  'Who can I talk to about my depression?',
  'What is loneliness?',
  'Im feeling lonely.',
  'Why am I having suicidal thoughts?',
  'Where can I find people like me?',
  'Nobody Likes Me',
  'What is gaslighting?',
  'My family members are abusive',
  'What is trauma?',
  'What is addiction?',
  'How can I stop drinking?',
  'I feel out of control',
  'How do I stop harming myself?',
  'How can I tell someone I’m harming myself?',
  'Am I harming myself? Types of self-harm',
  'How can connecting with others help my mental health?'
  
  
];
final faqanswer = [
  'What is anxiety?',
  'Anxiety is an emotion that you feel when you’re worried about something. Your body tenses up, and your mind becomes fixated on the thing you’re worried about. It can be hard to concentrate on anything else. ',
  'What are panic attacks?',
  'If you’ve ever experienced acute anxiety, you know how frightening panic attacks can be. Your body is responding in “fight-or-flight” mode to a threat that either doesn’t exist or one that doesn’t merit as extreme a reaction. They happen unexpectedly, even when you feel at ease.',
  'What’s the difference between anxiety and being stressed?',
  'The words stress and anxiety are sometimes used interchangeably.Both share many of the same physical symptoms, such as increased heart rate, muscle tension, or rapid breathing. In both cases, your body is releasing hormones to trigger these symptoms.',
  'Who can I talk to about my anxiety?',
  'When you’re experiencing an anxiety disorder, it’s easy to feel alone. It might feel like no one understands what you’re going through. You might not even fully understand it yourself! Reaching out can be scary, but there’s no need to suffer through anxiety on your own.Suggestions are Friends and Family,Professionals,Support groups and anonymous helplines',
  'How common is anxiety?',
  'Anxiety disorders are the most common mental health condition. If you or someone you love is experiencing anxiety, you’re not alone! ',
  'What is depression?',
  'Feeling sad is a normal human experience, but feeling too much sadness can cause distress and life problems. When too much sadness affects your life, you might have depression.',
  'Is depression curable?',
  'When someone is cured from an illness, it means it’s gone forever. Some illnesses can’t be cured—like diabetes. Once a person gets diabetes, they’ll have it for the rest of their life. But even a lifelong illness like diabetes can be treated. People who take their medications regularly and make some lifestyle changes can live long and healthy lives. These medications and lifestyle changes are treatments for diabetes.Depression is the same way. There’s no cure for depression, but there are lots of effective treatments. People can recover from depression and live long and healthy lives.',
  'What causes depression?',
  'Depression is a mental health problem that comes from changes in your brain. The changes relate to how your brain produces and absorbs neurotransmitters, how it’s circuits work, inflammation, and even how it’s built (grey matter). These biological changes can start because you have a family history of depression, or it can start after changes and stressors in your life.',
  'Does depression go away on its own??',
  'Depression affects everyone differently. For some people, it comes and goes. For others, it can feel almost constant. You might experience one episode of depression, or it might be a lifelong struggle.',
  'Who can I talk to about my depression?',
  'When you’re depressed, it’s easy to feel alone. It might feel like no one understands what you’re going through. You might not even fully understand it yourself! Reaching out can be scary, but there’s no need to suffer through depression on your own.Suggestions are Friends and Family,Professionals,Support groups and anonymous helplines',
  'What is loneliness?',
  'One common description of loneliness is the feeling we get when our need for rewarding social contact and relationships is not met. But loneliness is not always the same as being alone. You may choose to be alone and live happily without much contact with other people, while others may find this a lonely experience.',
  'Im feeling lonely.',
  'Humans are social animals—it’s in our nature to want to connect with others. When those needs aren’t being met, it’s completely normal to feel lonely. Loneliness is a universal emotion; we all feel it at one point or another.Sometimes it stems from us being isolated from other people. But often it sneaks up when you feel disconnected or misunderstood by the people around you. Feeling like you don’t “fit in” —with your classmates, with your friends, with society in general—is normal at any age.',
  'Why am I having suicidal thoughts?',
  'Suicidal thoughts are common—but it’s still very frightening to experience them. What are these feelings and thoughts building in your head? Why might you be focused on dying? Intrusive thoughts can momentarily interrupt your day—but having regular, distressing suicidal thoughts can cloud your mind for days, weeks, or months.',
  'Where can I find people like me?',
  'Living with a mental health condition can be isolating. It can feel like no one gets it, you can’t explain it, and you are the only one struggling. Loneliness tends to make whatever we’re experiencing worse – which then makes us want to isolate even further – which in turn makes us feel worse. It is an awful cycle.Most people want to feel connected and understood and want to have spaces where they feel like they belong. You can read about it, find an online community, find an inperson support group and share your story with people around you.',
  'Nobody Likes me',
  'We all want to be liked. When it seems like the world is against you, it’s easy to feel lonely, worthless, rejected. These feelings are real, and they run deep. We live in an interconnected world—people depend on each other to get their needs met. Your brain knows the importance of belonging. The strong emotions that come with not feeling liked or accepted are there to motivate you to connect more with others. ',
  'What is gaslighting?',
  'Gaslighting is a form of emotional abuse where a person makes you doubt yourself or question your account of an incident. Gaslighting can come from a romantic partner, a boss, a friend, or anyone else.',
  'My family members are abusive',
  'If you are being abused or neglected by your family, it can be as confusing as it is scary. Your natural reaction is to trust the people who are supposed to be caring for you, but under no circumstances is abuse acceptable. There are different types of abuse such as physical, verbal, sexual, psychological abuse, or neglect, but the bottom line is that a family member who is causing you physical or emotional harm is abusive.',
  'What is trauma?',
  'Sometimes when we see or experience something really scary, shocking, or harmful, the effects can stay with us for a long time after. If this is a familiar experience for you, you may be dealing with trauma. Anything that is highly stressful to you can be traumatic. Trauma is different for everyone—what seems normal to someone else might be traumatic for you.',
  'What is addiction?',
  'Sometimes people talk about addiction in a way that makes it seem like a moral failure—like people who struggle with addiction are “selfish” or “bad.” But addiction is actually a disorder of the brain. Addiction “hijacks” the reward pathways of your brain, making it physically more difficult to make healthy choices about your substance use. This means that addiction is a medical condition, just like heart disease or diabetes. It’s also a type of mental illness.',
  'How can I stop drinking?',
  'Any time you cut back on a habit-forming substance such as alcohol, your body goes through withdrawals. Your body has adapted to the amount you’ve been drinking, so cutting back throws your body out of balance. The most common symptoms of alcohol withdrawal include anxiety, nausea and vomiting, headaches, inability to sleep, sweating, and shaking. The more heavily you’ve been drinking, and the more quickly you stop, the more intense the symptoms will be.Start by talking to a doctor, who can give you recommendations based on your unique biology and situation. There are also medications that can make it easier to quit drinking. If you’ve been drinking heavily, try to decrease the amount of alcohol you drink gradually instead of quitting cold turkey.',
  'I feel out of control',
  'Whether you can’t stop snapping at people, can’t stop drinking, or can’t stop thinking stupid thoughts, feeling out of control can be frustrating. Sometimes it’s scary, and sometimes it’s exciting… until we wake up the next day and realize what we’ve done.It’s normal to feel out of control every once in a while. We all make mistakes and do things we regret. But if you find yourself losing control all the time, there’s probably more going on.',
  'How do I stop harming myself?',
  'Cutting (and other types of self-harm) may give you the sense of control you seek over your life or your body. Or maybe it helps you bury the pain that you don’t want to feel. But the only way to stop harming yourself is to face the pain. This is the recovery process: face the pain, work through it, and replace it with good experiences. In the past, you may have turned to self-harm as a coping mechanism, but now you’ve decided to seek a different way to cope. This is an important first step in stopping self-harm. Getting better is going to take some time—but it’s possible.',
  'How can I tell someone I’m harming myself?',
  'The person you choose to tell about self-harm plays an important role in your experience. Think about your reason for telling someone. If you are hoping to feel less alone, you may want to tell a close friend or peer. If you’re looking for help, a family member or other trusted adult (like a coach, teacher, or school guidance counselor) can help you figure out where to start. You can also confide in your doctor, therapist, or another healthcare professional.',
  'Am I harming myself? Types of self-harm',
  'Self-harm refers to anything that someone does to intentionally hurt themselves—or something that they know is harmful but do anyway.Self-harm is a maladaptive coping mechanism: something that may make you feel better in the moment, but is harmful overall. Most conversations about self-harm focus on cutting. Some of the types are Physical self-harm, Alcohol and Drug misue,Disordered eating,self neglect and self destructive behaviour',
  'How can connecting with others help my mental health?',
  'Sometimes connection is a heart-to-heart, spill-it-all-out talk. But sometimes it’s just a funny text or meme. There are benefits of social connection. Some of these benefits may include increased happiness and living a longer, healthier life. Connections with other people are good for our mental health and well-being. No matter how we connect with others, it helps us improve our health, stress, and overall quality of life.'
  
 
  ];

